// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: chunk_getter.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChunkGetterClient is the client API for ChunkGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkGetterClient interface {
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkReply, error)
}

type chunkGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkGetterClient(cc grpc.ClientConnInterface) ChunkGetterClient {
	return &chunkGetterClient{cc}
}

func (c *chunkGetterClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkReply, error) {
	out := new(GetChunkReply)
	err := c.cc.Invoke(ctx, "/recryptor.ChunkGetter/GetChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkGetterServer is the server API for ChunkGetter service.
// All implementations must embed UnimplementedChunkGetterServer
// for forward compatibility
type ChunkGetterServer interface {
	GetChunk(context.Context, *GetChunkRequest) (*GetChunkReply, error)
	mustEmbedUnimplementedChunkGetterServer()
}

// UnimplementedChunkGetterServer must be embedded to have forward compatible implementations.
type UnimplementedChunkGetterServer struct {
}

func (UnimplementedChunkGetterServer) GetChunk(context.Context, *GetChunkRequest) (*GetChunkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedChunkGetterServer) mustEmbedUnimplementedChunkGetterServer() {}

// UnsafeChunkGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkGetterServer will
// result in compilation errors.
type UnsafeChunkGetterServer interface {
	mustEmbedUnimplementedChunkGetterServer()
}

func RegisterChunkGetterServer(s grpc.ServiceRegistrar, srv ChunkGetterServer) {
	s.RegisterService(&ChunkGetter_ServiceDesc, srv)
}

func _ChunkGetter_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkGetterServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recryptor.ChunkGetter/GetChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkGetterServer).GetChunk(ctx, req.(*GetChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkGetter_ServiceDesc is the grpc.ServiceDesc for ChunkGetter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkGetter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recryptor.ChunkGetter",
	HandlerType: (*ChunkGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChunk",
			Handler:    _ChunkGetter_GetChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chunk_getter.proto",
}
