// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: rate_limiter.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteAddr string `protobuf:"bytes,1,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query      string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Token      []byte `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Guide      []byte `protobuf:"bytes,5,opt,name=guide,proto3" json:"guide,omitempty"`
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_limiter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *RateLimitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RateLimitRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RateLimitRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RateLimitRequest) GetGuide() []byte {
	if x != nil {
		return x.Guide
	}
	return nil
}

type RateLimitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RateLimitReply) Reset() {
	*x = RateLimitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_limiter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitReply) ProtoMessage() {}

func (x *RateLimitReply) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitReply.ProtoReflect.Descriptor instead.
func (*RateLimitReply) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_rate_limiter_proto protoreflect.FileDescriptor

var file_rate_limiter_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x72, 0x22,
	0x88, 0x01, 0x0a, 0x10, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x75, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x67, 0x75, 0x69, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x53, 0x0a, 0x0b,
	0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x08, 0x43,
	0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x6c, 0x66, 0x69, 0x6e, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x65, 0x6c, 0x66, 0x69, 0x6e, 0x68,
	0x6f, 0x73, 0x74, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x72, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rate_limiter_proto_rawDescOnce sync.Once
	file_rate_limiter_proto_rawDescData = file_rate_limiter_proto_rawDesc
)

func file_rate_limiter_proto_rawDescGZIP() []byte {
	file_rate_limiter_proto_rawDescOnce.Do(func() {
		file_rate_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_rate_limiter_proto_rawDescData)
	})
	return file_rate_limiter_proto_rawDescData
}

var file_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rate_limiter_proto_goTypes = []interface{}{
	(*RateLimitRequest)(nil), // 0: recryptor.RateLimitRequest
	(*RateLimitReply)(nil),   // 1: recryptor.RateLimitReply
}
var file_rate_limiter_proto_depIdxs = []int32{
	0, // 0: recryptor.RateLimiter.CanServe:input_type -> recryptor.RateLimitRequest
	1, // 1: recryptor.RateLimiter.CanServe:output_type -> recryptor.RateLimitReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rate_limiter_proto_init() }
func file_rate_limiter_proto_init() {
	if File_rate_limiter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rate_limiter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_limiter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rate_limiter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rate_limiter_proto_goTypes,
		DependencyIndexes: file_rate_limiter_proto_depIdxs,
		MessageInfos:      file_rate_limiter_proto_msgTypes,
	}.Build()
	File_rate_limiter_proto = out.File
	file_rate_limiter_proto_rawDesc = nil
	file_rate_limiter_proto_goTypes = nil
	file_rate_limiter_proto_depIdxs = nil
}
